name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      # Build the package
      - name: Build the package
        run: |
          python -m build

      # Publish to PyPI
      - name: Publish to PyPI
        uses: pypi/gh-action-publish-to-pypi@v1.5.0
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
